### PR TITLE
Remove unnecessary </path>

### PR DESCRIPTION
**Pull request by onejmi**
All the present path tags have corresponding ones which close them. Instead, closing those tags in the opening bracket would reduce the amount of code being written and retain the same result.

### CODE REVIEW

**Review by hamirmahal — APPROVED** [review]
I was just about to create a new pull request for the same issue.

**Comment by hamirmahal** [comment]
@tholman are you open to accepting this pull request?

This is a really excellent repository. Thank you for making it open-source.

**Comment by tholman** [comment]
Thanks! Sorry for the infinitely slow from me, I get lost in all my projects!

**Comment by tholman** [comment]
Now to remember how I deployed this :D

**Pull request merged**
