### PR TITLE
MIT is called out in README, create actual file

### PR DESCRIPTION
**Pull request by brntbeer**
hi @desandro! Sorry for the terrible branch name, but I thought it'd be good to include the actual file itself in this PR.

Great repo by the way, love the new ribbon.

### CODE REVIEW

**Comment by tholman** [comment]
Hey man, I appreciate this, big time!

But I think its fine just giving the mention. People definitely get it... and I kind of have this strange thing against adding more and more to a repo ( even if it is a licence... perhaps I'm a little bit strange :S )

**Comment by brntbeer** [comment]
@tholman understandable! Just wanting to urge a bit of caution for just mentioning it in the README, while it's better than nothing, this is kind of below the norm. More info on importances from GitHub's open source license-guru here: https://github.com/benbalter/licensee/issues/4

**Comment by benbalter** [comment]
Also to note, the [usage instructions for the license](http://choosealicense.com/licenses/mit/) direct project maintainers to:

> Create a text file (typically named LICENSE or LICENSE.txt) in the root of your source code and copy the text of the license into the file. Replace [year] with the current year and [fullname] with the name (or names) of the copyright holders.

**Comment by tholman** [comment]
Added it now, so we can all sleep easy :)

**Pull request closed without merging**
