### PR TITLE
add z-index

### PR DESCRIPTION
**Pull request by calvinmetcalf**
adds a z-index so it will be properly above everything on the page

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
see example with z-index set [here](http://calvinmetcalf.github.io/parcel-map/) without z-index it ends up under the map

**Comment by tholman** [comment]
Appreciate this... I'm kind of following loosely the same code the original ribbons used - https://github.com/blog/273-github-ribbons ... I don't really think its fair to inject a 9999 z index on someones page (when they may have their own system of doing things)

Going to be a little rash, and say anyone who puts the corner in there, and can't see why its appearing below their content, will be clever enough to add in their own index.

Thanks though!

**Comment by calvinmetcalf** [comment]
you might be overestimating the general public's experience with css as I'm not a new comer to html but am embarked to say I had to look up in the old version how they got it to appear above the map. So maybe a note above that in the docs would be a good idea.

I'd also be somewhat curious about what kind of issues injecting a 9999 z index could cause on a page.

**Comment by mkody** [comment]
> I'd also be somewhat curious about what kind of issues injecting a 9999 z index could cause on a page.

@calvinmetcalf An exemple: 
If I put a [Lightbox](https://en.wikipedia.org/wiki/Lightbox_(JavaScript)) showing some pictures on my page, it's nice to have the ribbon _behind_ the Lightbox and not having the ribbon go by itself in front of everything.

**Comment by calvinmetcalf** [comment]
Ah right or if you have a bootstrap model open that makes sense thanks

**Pull request closed without merging**
